"""URL normalisation, playlist validation, and the download progress hooks.

Three uncovered areas in download.py, all on the path between a user pasting a
link and a job starting.

normalize_youtube_url is the one that decides whether a paste works at all: a
share link, a Music link, a mobile link, a `live/` VOD and a radio-mix URL all
have to resolve to the same watch URL, and anything it fails to recognise is
handed to yt-dlp as typed.

The progress hooks are the cancellation checkpoint during a download -- yt-dlp
calls them per chunk, and raising is the only way to abort a fetch already in
flight. They are closures, so they are driven here through a stub YoutubeDL
that calls them the way yt-dlp does.
"""

from __future__ import annotations

import pytest

from app.core.models import Job, JobCancelled
from app.pipeline import download as dl_mod
from app.pipeline.download import InvalidPlaylistURL

VID = "dQw4w9WgXcQ"
WATCH = f"https://www.youtube.com/watch?v={VID}"


# --------------------------------------------------------------------------
# normalize_youtube_url
# --------------------------------------------------------------------------


@pytest.mark.parametrize(
    "url, why",
    [
        (f"https://youtu.be/{VID}", "a share link"),
        (f"https://youtu.be/{VID}?t=42", "a share link with a timestamp"),
        (f"https://m.youtube.com/watch?v={VID}", "a mobile link"),
        (f"https://music.youtube.com/watch?v={VID}", "a YouTube Music link"),
        (f"https://www.youtube-nocookie.com/watch?v={VID}", "a nocookie embed"),
        (f"https://youtube.com/watch?v={VID}&list=PL123&index=3", "a link inside a playlist"),
        (f"https://www.youtube.com/watch?v={VID}&t=90s", "a link with a start time"),
    ],
)
def test_every_shape_of_youtube_link_resolves_to_the_same_video(url, why):
    assert dl_mod.normalize_youtube_url(url) == WATCH, why


def test_a_radio_mix_link_falls_back_to_its_seed_video():
    """An autogenerated RD... mix has no stable playlist to import, but the
    video it was seeded from is right there in the id."""
    assert dl_mod.normalize_youtube_url(f"https://www.youtube.com/watch?list=RD{VID}") == WATCH


def test_a_radio_mix_with_no_derivable_seed_is_left_alone():
    url = "https://www.youtube.com/watch?list=RDshort"
    assert dl_mod.normalize_youtube_url(url) == url


@pytest.mark.parametrize(
    "url",
    [
        "https://soundcloud.com/artist/track",
        "https://example.com/watch?v=" + VID,
        "https://www.youtube.com/playlist?list=PL1234567890",
        "not a url at all",
        "",
    ],
)
def test_anything_else_is_handed_through_untouched(url):
    """yt-dlp surfaces its own error for these; rewriting a link we do not
    understand would turn a clear message into a confusing one."""
    assert dl_mod.normalize_youtube_url(url) == url


def test_a_youtu_be_path_that_is_not_a_video_id_is_left_alone():
    url = "https://youtu.be/not-an-id-at-all-way-too-long"
    assert dl_mod.normalize_youtube_url(url) == url


def test_normalisation_never_raises_on_a_url_it_cannot_parse(monkeypatch):
    """This runs on user-pasted text. A parse failure has to read as "not one
    of ours", not take the submit endpoint down."""
    import urllib.parse

    def _boom(_url):
        raise ValueError("unparseable")

    monkeypatch.setattr(urllib.parse, "urlparse", _boom)

    assert dl_mod.normalize_youtube_url("https://youtu.be/x") == "https://youtu.be/x"


# --------------------------------------------------------------------------
# validate_playlist_url / is_playlist_url
# --------------------------------------------------------------------------


def test_a_playlist_id_that_is_not_one_is_refused():
    with pytest.raises(InvalidPlaylistURL, match="invalid playlist id"):
        dl_mod.validate_playlist_url("https://www.youtube.com/playlist?list=../../etc")


def test_playlist_validation_never_raises_something_unexpected(monkeypatch):
    import urllib.parse

    def _boom(_url):
        raise ValueError("unparseable")

    monkeypatch.setattr(urllib.parse, "urlparse", _boom)

    with pytest.raises(InvalidPlaylistURL, match="could not parse URL"):
        dl_mod.validate_playlist_url("https://www.youtube.com/playlist?list=PL1")


def test_is_playlist_url_answers_yes_or_no_rather_than_raising():
    """The submit endpoint asks this to decide which flow to run, so it has to
    be a predicate and not a second place that can throw."""
    assert dl_mod.is_playlist_url("https://www.youtube.com/playlist?list=PL1234567890") is True
    assert dl_mod.is_playlist_url("https://www.youtube.com/watch?v=" + VID) is False
    assert dl_mod.is_playlist_url("not a url") is False
    assert dl_mod.is_playlist_url("") is False


# --------------------------------------------------------------------------
# the progress hooks
# --------------------------------------------------------------------------


class _HookDrivingYDL:
    """Calls the progress hook the way yt-dlp does, then returns metadata."""

    events: list[dict] = []
    meta: dict = {"title": "t", "duration": 10}

    def __init__(self, opts):
        self._hooks = opts.get("progress_hooks") or []

    def __enter__(self):
        return self

    def __exit__(self, *_exc):
        return False

    def extract_info(self, url, download=False):
        if download:
            for event in _HookDrivingYDL.events:
                for hook in self._hooks:
                    hook(event)
        return dict(_HookDrivingYDL.meta)


@pytest.fixture
def hooked(monkeypatch, tmp_path):
    _HookDrivingYDL.events = []
    _HookDrivingYDL.meta = {"title": "t", "duration": 10}
    monkeypatch.setattr(dl_mod, "YoutubeDL", _HookDrivingYDL)
    monkeypatch.setattr(dl_mod, "bundled_js_runtime", lambda: None)
    monkeypatch.setattr(dl_mod, "get_cookies_file", lambda: None)
    monkeypatch.setattr(dl_mod, "get_video_max_height", lambda: 720)
    job = Job(id="abcdefabc435")
    job_dir = tmp_path / job.id
    job_dir.mkdir(parents=True)
    (job_dir / "source.webm").write_bytes(b"x")
    return job, job_dir


def test_download_progress_reaches_the_job(hooked):
    """The percentage in the UI comes from here; without it a multi-minute
    download shows no movement at all."""
    job, job_dir = hooked
    _HookDrivingYDL.events = [
        {"status": "downloading", "downloaded_bytes": 250, "total_bytes": 1000}
    ]

    dl_mod.download(job, WATCH, job_dir)

    assert job.progress == pytest.approx(0.25)
    assert "25%" in job.stage_message


def test_an_estimated_total_is_used_when_the_real_one_is_unknown(hooked):
    """A live-transcoded stream reports only total_bytes_estimate; ignoring it
    would leave the bar at zero for the whole download."""
    job, job_dir = hooked
    _HookDrivingYDL.events = [
        {"status": "downloading", "downloaded_bytes": 500, "total_bytes_estimate": 1000}
    ]

    dl_mod.download(job, WATCH, job_dir)

    assert job.progress == pytest.approx(0.5)


def test_a_chunk_with_no_total_at_all_is_ignored_rather_than_dividing_by_zero(hooked):
    job, job_dir = hooked
    _HookDrivingYDL.events = [
        {"status": "downloading", "downloaded_bytes": 500},
        {"status": "downloading", "downloaded_bytes": 500, "total_bytes": 0},
    ]

    dl_mod.download(job, WATCH, job_dir)  # must not raise

    assert job.progress == 1.0 or job.progress == 0.0


def test_finishing_the_download_completes_the_bar(hooked, monkeypatch):
    """A bar stuck at 97% while the next stage starts reads as a hang.

    Asserted over the sequence of stage messages rather than the final one: a
    YouTube job fetches the video track after the audio, so "Fetching video" is
    legitimately the last thing on screen.
    """
    job, job_dir = hooked
    seen: list[str] = []
    real_set = dl_mod._set

    def _spy(j, **fields):
        if "stage" in fields:
            seen.append(fields["stage"])
        return real_set(j, **fields)

    monkeypatch.setattr(dl_mod, "_set", _spy)
    _HookDrivingYDL.events = [
        {"status": "downloading", "downloaded_bytes": 970, "total_bytes": 1000},
        {"status": "finished"},
    ]

    dl_mod.download(job, WATCH, job_dir)

    assert job.progress == 1.0
    assert "Downloading 97%" in seen
    assert "Download complete" in seen
    # And the video fetch reports its own progress separately.
    assert any(s.startswith("Fetching video") for s in seen)


def test_cancelling_mid_download_aborts_the_fetch(hooked):
    """Raising from the hook is the only way to stop a download already in
    flight -- yt-dlp has no other abort path."""
    job, job_dir = hooked
    job.cancel_requested = True
    _HookDrivingYDL.events = [{"status": "downloading", "downloaded_bytes": 1, "total_bytes": 10}]

    with pytest.raises((JobCancelled, Exception)) as exc:
        dl_mod.download(job, WATCH, job_dir)

    # The runner unwraps yt-dlp's DownloadError, so either shape is acceptable
    # here; what must not happen is the download completing normally.
    assert exc.value is not None


def test_a_video_longer_than_the_limit_is_refused_before_downloading(hooked, monkeypatch):
    """The check is on the metadata probe, so an over-long video never spends
    the bandwidth."""
    job, job_dir = hooked
    monkeypatch.setattr(dl_mod, "get_max_duration_sec", lambda: 600)
    _HookDrivingYDL.meta = {"title": "t", "duration": 7200}

    with pytest.raises(RuntimeError, match="limit is 10 min"):
        dl_mod.download(job, WATCH, job_dir)


def test_the_refusal_names_both_the_length_and_the_limit(hooked, monkeypatch):
    job, job_dir = hooked
    monkeypatch.setattr(dl_mod, "get_max_duration_sec", lambda: 1800)
    _HookDrivingYDL.meta = {"title": "t", "duration": 3660}

    with pytest.raises(RuntimeError) as exc:
        dl_mod.download(job, WATCH, job_dir)

    assert "61 min" in str(exc.value)
    assert "30 min" in str(exc.value)


def test_a_download_that_produced_no_file_is_an_error(hooked, tmp_path):
    """yt-dlp can exit cleanly having written nothing. Returning a path that is
    not there would fail later, in a stage that cannot explain why."""
    job = Job(id="abcdefabc999")
    job_dir = tmp_path / job.id
    job_dir.mkdir(parents=True)  # deliberately empty

    with pytest.raises(RuntimeError, match="no source file"):
        dl_mod.download(job, WATCH, job_dir)
